#############################################################################
# Makefile for building: FlappyBird.app/Contents/MacOS/FlappyBird
# Generated by qmake (3.1) (Qt 6.6.2)
# Project:  FlappyBird.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile FlappyBird.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/opt/homebrew/lib/QtWidgets.framework/Headers -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/share/qt/mkspecs/macx-clang -F/opt/homebrew/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FlappyBird1.0.0
<<<<<<< HEAD
DISTDIR = /mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8/.tmp/FlappyBird1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
=======
DISTDIR = /Users/laylaelattar/Desktop/group8/.tmp/FlappyBird1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/opt/homebrew/lib
LIBS          = $(SUBLIBS) -F/opt/homebrew/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/game.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/object.cpp \
		src/background.cpp \
		src/collidableObject.cpp \
		src/obstacle.cpp \
		src/player.cpp \
		src/highscore.cpp moc_Game.cpp \
		moc_mainwindow.cpp \
		moc_Object.cpp \
		moc_HighScore.cpp
OBJECTS       = game.o \
		main.o \
		mainwindow.o \
		object.o \
		background.o \
		collidableObject.o \
		obstacle.o \
		player.o \
		highscore.o \
		moc_Game.o \
		moc_mainwindow.o \
<<<<<<< HEAD
		moc_Object.o \
		moc_HighScore.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
=======
		moc_Object.o
DIST          = /opt/homebrew/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/share/qt/mkspecs/features/spec_post.prf \
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0
		.qmake.stash \
		/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/share/qt/mkspecs/features/permissions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt.prf \
		/opt/homebrew/share/qt/mkspecs/features/resources_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/resources.prf \
		/opt/homebrew/share/qt/mkspecs/features/moc.prf \
		/opt/homebrew/share/qt/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/share/qt/mkspecs/features/uic.prf \
		/opt/homebrew/share/qt/mkspecs/features/unix/thread.prf \
		/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/share/qt/mkspecs/features/lex.prf \
		FlappyBird.pro headers/Game.h \
		headers/mainwindow.h \
		headers/Object.h \
		headers/Background.h \
		headers/CollidableObject.h \
		headers/Obstacle.h \
		headers/Player.h \
		headers/HighScore.h src/game.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/object.cpp \
		src/background.cpp \
		src/collidableObject.cpp \
		src/obstacle.cpp \
		src/player.cpp \
		src/highscore.cpp
QMAKE_TARGET  = FlappyBird
DESTDIR       = 
TARGET        = FlappyBird.app/Contents/MacOS/FlappyBird

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/laylaelattar/Desktop/group8/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/laylaelattar/Desktop/group8/FlappyBird.pro


include /opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

FlappyBird.app/Contents/MacOS/FlappyBird:  $(OBJECTS)  
	@test -d FlappyBird.app/Contents/MacOS/ || mkdir -p FlappyBird.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FlappyBird.pro /opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf /opt/homebrew/share/qt/mkspecs/features/spec_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang-mac.conf \
		/opt/homebrew/share/qt/mkspecs/qconfig.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt_config.prf \
		/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/share/qt/mkspecs/features/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf \
		/opt/homebrew/share/qt/mkspecs/features/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf \
		/opt/homebrew/share/qt/mkspecs/features/warn_on.prf \
		/opt/homebrew/share/qt/mkspecs/features/permissions.prf \
		/opt/homebrew/share/qt/mkspecs/features/qt.prf \
		/opt/homebrew/share/qt/mkspecs/features/resources_functions.prf \
		/opt/homebrew/share/qt/mkspecs/features/resources.prf \
		/opt/homebrew/share/qt/mkspecs/features/moc.prf \
		/opt/homebrew/share/qt/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/share/qt/mkspecs/features/uic.prf \
		/opt/homebrew/share/qt/mkspecs/features/unix/thread.prf \
		/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf \
		/opt/homebrew/share/qt/mkspecs/features/file_copies.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf \
		/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/share/qt/mkspecs/features/exceptions.prf \
		/opt/homebrew/share/qt/mkspecs/features/yacc.prf \
		/opt/homebrew/share/qt/mkspecs/features/lex.prf \
		FlappyBird.pro \
		/opt/homebrew/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile FlappyBird.pro
/opt/homebrew/share/qt/mkspecs/features/spec_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt/6.6.2_1/share/qt/mkspecs/common/clang-mac.conf:
/opt/homebrew/share/qt/mkspecs/qconfig.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_graphs_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_grpc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/opt/homebrew/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/opt/homebrew/share/qt/mkspecs/features/qt_functions.prf:
/opt/homebrew/share/qt/mkspecs/features/qt_config.prf:
/opt/homebrew/share/qt/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/share/qt/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/sdk.prf:
/opt/homebrew/share/qt/mkspecs/features/toolchain.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/share/qt/mkspecs/features/default_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/share/qt/mkspecs/features/resolve_config.prf:
/opt/homebrew/share/qt/mkspecs/features/default_post.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/default_post.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/mac.prf:
/opt/homebrew/share/qt/mkspecs/features/warn_on.prf:
/opt/homebrew/share/qt/mkspecs/features/permissions.prf:
/opt/homebrew/share/qt/mkspecs/features/qt.prf:
/opt/homebrew/share/qt/mkspecs/features/resources_functions.prf:
/opt/homebrew/share/qt/mkspecs/features/resources.prf:
/opt/homebrew/share/qt/mkspecs/features/moc.prf:
/opt/homebrew/share/qt/mkspecs/features/unix/opengl.prf:
/opt/homebrew/share/qt/mkspecs/features/uic.prf:
/opt/homebrew/share/qt/mkspecs/features/unix/thread.prf:
/opt/homebrew/share/qt/mkspecs/features/qmake_use.prf:
/opt/homebrew/share/qt/mkspecs/features/file_copies.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/rez.prf:
/opt/homebrew/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/share/qt/mkspecs/features/testcase_targets.prf:
/opt/homebrew/share/qt/mkspecs/features/exceptions.prf:
/opt/homebrew/share/qt/mkspecs/features/yacc.prf:
/opt/homebrew/share/qt/mkspecs/features/lex.prf:
FlappyBird.pro:
/opt/homebrew/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FlappyBird.pro

qmake_all: FORCE

FlappyBird.app/Contents/PkgInfo: 
	@test -d FlappyBird.app/Contents || mkdir -p FlappyBird.app/Contents
	@$(DEL_FILE) FlappyBird.app/Contents/PkgInfo
	@echo "APPL????" > FlappyBird.app/Contents/PkgInfo
FlappyBird.app/Contents/Info.plist: 
	@test -d FlappyBird.app/Contents || mkdir -p FlappyBird.app/Contents
	@$(DEL_FILE) FlappyBird.app/Contents/Info.plist
	@plutil -convert xml1 -o - /opt/homebrew/share/qt/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.FlappyBird,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.FlappyBird,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},14.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,FlappyBird,g" -e "s,@LIBRARY@,FlappyBird,g" -e "s,\$${EXECUTABLE_NAME},FlappyBird,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >FlappyBird.app/Contents/Info.plist

all: Makefile \
		FlappyBird.app/Contents/PkgInfo \
		FlappyBird.app/Contents/Info.plist FlappyBird.app/Contents/MacOS/FlappyBird

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents headers/Game.h headers/mainwindow.h headers/Object.h headers/Background.h headers/CollidableObject.h headers/Obstacle.h headers/Player.h headers/HighScore.h $(DISTDIR)/
	$(COPY_FILE) --parents src/game.cpp src/main.cpp src/mainwindow.cpp src/object.cpp src/background.cpp src/collidableObject.cpp src/obstacle.cpp src/player.cpp src/highscore.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r FlappyBird.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.0 -Wall -Wextra -dM -E -o moc_predefs.h /opt/homebrew/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Game.cpp moc_mainwindow.cpp moc_Object.cpp moc_HighScore.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Game.cpp moc_mainwindow.cpp moc_Object.cpp moc_HighScore.cpp
moc_Game.cpp: headers/Game.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/Background.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		headers/Obstacle.h \
		headers/CollidableObject.h \
		headers/HighScore.h \
		headers/Player.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/lib/QtGui.framework/Headers/qevent.h \
		moc_predefs.h \
<<<<<<< HEAD
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include headers/Game.h -o moc_Game.cpp
=======
		/opt/homebrew/share/qt/libexec/moc
	/opt/homebrew/share/qt/libexec/moc $(DEFINES) --include /Users/laylaelattar/Desktop/group8/moc_predefs.h -I/opt/homebrew/share/qt/mkspecs/macx-clang -I/Users/laylaelattar/Desktop/group8 -I/opt/homebrew/lib/QtWidgets.framework/Headers -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtCore.framework/Headers -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -F/opt/homebrew/lib headers/Game.h -o moc_Game.cpp
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0

moc_mainwindow.cpp: headers/mainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGridLayout \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsView \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		moc_predefs.h \
<<<<<<< HEAD
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include headers/mainwindow.h -o moc_mainwindow.cpp
=======
		/opt/homebrew/share/qt/libexec/moc
	/opt/homebrew/share/qt/libexec/moc $(DEFINES) --include /Users/laylaelattar/Desktop/group8/moc_predefs.h -I/opt/homebrew/share/qt/mkspecs/macx-clang -I/Users/laylaelattar/Desktop/group8 -I/opt/homebrew/lib/QtWidgets.framework/Headers -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtCore.framework/Headers -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -F/opt/homebrew/lib headers/mainwindow.h -o moc_mainwindow.cpp
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0

moc_Object.cpp: headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		moc_predefs.h \
<<<<<<< HEAD
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include headers/Object.h -o moc_Object.cpp

moc_HighScore.cpp: headers/HighScore.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/theo/Documents/repoCS/3307/cloneRepo/group8 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include headers/HighScore.h -o moc_HighScore.cpp
=======
		/opt/homebrew/share/qt/libexec/moc
	/opt/homebrew/share/qt/libexec/moc $(DEFINES) --include /Users/laylaelattar/Desktop/group8/moc_predefs.h -I/opt/homebrew/share/qt/mkspecs/macx-clang -I/Users/laylaelattar/Desktop/group8 -I/opt/homebrew/lib/QtWidgets.framework/Headers -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtCore.framework/Headers -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include -F/opt/homebrew/lib headers/Object.h -o moc_Object.cpp
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

game.o: src/game.cpp headers/Game.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/Background.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		headers/Obstacle.h \
		headers/CollidableObject.h \
<<<<<<< HEAD
		headers/HighScore.h \
		headers/Player.h
=======
		headers/Player.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsView \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QGuiApplication \
		/opt/homebrew/lib/QtGui.framework/Headers/qguiapplication.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QScreen \
		/opt/homebrew/lib/QtGui.framework/Headers/qscreen.h
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o src/game.cpp

main.o: src/main.cpp headers/mainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGridLayout \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsView \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp headers/mainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGridLayout \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsView \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QGraphicsProxyWidget \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		headers/Game.h \
		headers/Background.h \
		headers/Object.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		headers/Obstacle.h \
		headers/CollidableObject.h \
<<<<<<< HEAD
		headers/HighScore.h \
		headers/Player.h
=======
		headers/Player.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/lib/QtGui.framework/Headers/qevent.h
>>>>>>> d7faa321b2cfd036deb8a1f972c40ac674b179e0
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

object.o: src/object.cpp headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o src/object.cpp

background.o: src/background.cpp headers/Background.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QGuiApplication \
		/opt/homebrew/lib/QtGui.framework/Headers/qguiapplication.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QScreen \
		/opt/homebrew/lib/QtGui.framework/Headers/qscreen.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o background.o src/background.cpp

collidableObject.o: src/collidableObject.cpp headers/CollidableObject.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QGuiApplication \
		/opt/homebrew/lib/QtGui.framework/Headers/qguiapplication.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QScreen \
		/opt/homebrew/lib/QtGui.framework/Headers/qscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collidableObject.o src/collidableObject.cpp

obstacle.o: src/obstacle.cpp headers/Obstacle.h \
		headers/CollidableObject.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QGuiApplication \
		/opt/homebrew/lib/QtGui.framework/Headers/qguiapplication.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QScreen \
		/opt/homebrew/lib/QtGui.framework/Headers/qscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obstacle.o src/obstacle.cpp

player.o: src/player.cpp headers/Player.h \
		headers/CollidableObject.h \
		headers/Object.h \
		/opt/homebrew/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QPixmap \
		/opt/homebrew/lib/QtGui.framework/Headers/qpixmap.h \
		/opt/homebrew/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o src/player.cpp

highscore.o: src/highscore.cpp headers/HighScore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highscore.o src/highscore.cpp

moc_Game.o: moc_Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Game.o moc_Game.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_Object.o: moc_Object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Object.o moc_Object.cpp

moc_HighScore.o: moc_HighScore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HighScore.o moc_HighScore.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

